# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: trivy_image_scan

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main


permissions:
  contents: read

jobs:
    trivy_image_scan_dlstreamer:
      permissions:
        contents: read # for actions/checkout to fetch code
        security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
        actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
      name: trivy_image_scan
      runs-on: "ubuntu-latest"
      steps:
        - name: Checkout code for Pull Request
          if: github.event_name == 'pull_request'
          uses: actions/checkout@1e31de5234b9f8995739874a8ce0492dc87873e2
          with:
            repository: ${{ github.event.pull_request.head.repo.full_name }}
            ref: ${{ github.event.pull_request.head.ref }}
        - name: Checkout code for Push Request
          if: github.event_name == 'push'
          uses: actions/checkout@1e31de5234b9f8995739874a8ce0492dc87873e2
          with:
            ref: main
        - name: Build an image from Dockerfile
          run: |
            echo "running make build benchmark"
            make build
          env:
            REGISTRY: "false"

        - name: Extract ASC value from VERSION file
          id: extract_asc
          run: |
            pwd
            ls -ltra
            ASC_TAG=$(grep '^ASC=' VERSION | cut -d= -f2)
            echo "ASC_TAG=$ASC_TAG" >> $GITHUB_OUTPUT
          
        - name: Run Trivy vulnerability scanner
          uses: aquasecurity/trivy-action@915b19bbe73b92a6cf82a1bc12b087c9a19a5fe2
          with:
            image-ref: 'pipeline-runner-asc:${{ steps.extract_asc.outputs.ASC_TAG}}'
            format: 'table'
            severity: 'CRITICAL,HIGH'
            output: 'trivy-asc-results.txt'

        - name: Upload Trivy scan results
          uses: actions/upload-artifact@v4
          with:
            name: trivy-html-report
            path: trivy-asc-results.txt
